#define  AUTOOPTS_INTERNAL 1
#include "../../../../sntp/libopts/autoopts/project.h"
#define  LOCAL static
#include "../../../../sntp/libopts/ao-strs.h"
static char const ao_ver_string[] =
    "41:0:16\n";
#include "../../../../sntp/libopts/autoopts/options.h"
#include "../../../../sntp/libopts/autoopts/usage-txt.h"
#include "../../../../sntp/libopts/genshell.h"
#include "../../../../sntp/libopts/option-xat-attribute.h"
#include "../../../../sntp/libopts/option-value-type.h"
#include "../../../../sntp/libopts/ao-strs.h"
#include "../../../../sntp/libopts/ag-char-map.h"
#include "../../../../sntp/libopts/autoopts.h"
#include "proto.h"
#include "../../../../sntp/libopts/parse-duration.c"
#include "../../../../sntp/libopts/ao-strs.c"
#include "../../../../sntp/libopts/option-value-type.c"
#include "../../../../sntp/libopts/option-xat-attribute.c"
#include "../../../../sntp/libopts/autoopts.c"
#include "../../../../sntp/libopts/alias.c"
#include "../../../../sntp/libopts/boolean.c"
#include "../../../../sntp/libopts/check.c"
#include "../../../../sntp/libopts/configfile.c"
#include "../../../../sntp/libopts/cook.c"
#include "../../../../sntp/libopts/enum.c"
#include "../../../../sntp/libopts/env.c"
#include "../../../../sntp/libopts/file.c"
#include "../../../../sntp/libopts/find.c"
#include "../../../../sntp/libopts/genshell.c"
#include "../../../../sntp/libopts/load.c"
#include "makeshell.c"
#include "../../../../sntp/libopts/nested.c"
#include "../../../../sntp/libopts/numeric.c"
#include "../../../../sntp/libopts/pgusage.c"
#include "../../../../sntp/libopts/putshell.c"
#include "../../../../sntp/libopts/reset.c"
#include "../../../../sntp/libopts/restore.c"
#include "../../../../sntp/libopts/save.c"
#include "../../../../sntp/libopts/sort.c"
#include "../../../../sntp/libopts/stack.c"
#include "../../../../sntp/libopts/streqvcmp.c"
#include "../../../../sntp/libopts/text_mmap.c"
#include "../../../../sntp/libopts/time.c"
#include "../../../../sntp/libopts/tokenize.c"
#include "../../../../sntp/libopts/usage.c"
#include "../../../../sntp/libopts/version.c"
#include "../../../../sntp/libopts/init.c"
